---
title: "Haar Heatmap Masking/NN prep (Sobel)"
author: "Zach Diener"
date: "June 29, 2015"
output: html_document
---


#Sobel Operators
```{r}
library(wavethresh) 
library(gplots)
library(wavelets)

set.seed(5)

rm(list=ls())	#Clear data

sds<-sample(rep(c(0,0.2,0.4,0.6,0.8,1.0,1.2,1.4,1.6,1.8,2.0),30))	#Generate random list of standard deviations
TestCases<-data.frame(matrix(NA,nrow=330,ncol=70))	#Create empty data frame to store simulated signals
NoiseSeeds<-data.frame(matrix(NA,nrow=330,ncol=626))	#Create empty data frame to store state of RNG before each injection of noise
SD_Change<-data.frame(matrix(NA,nrow=330,ncol=2))	#Create empty data frame to store standard deviations and transition points
colnames(SD_Change)<-c("sd","change")	#Name columns 
x<-(1:70)	#Create vector of values from 1 to 70
for(i in 1:330){	#Loop over all standard deviations
		change1<-sample(25:55,1)	#Randomly select transition point between 25 and 55
		NoiseSeeds[i,]<-.Random.seed	#Store state of RNG
		TestCases[i,(1:70)]<-(((x>=1 & x<(change1-25))*0)+((x>=(change1-25) & x<(change1-10))*((0.02*x)+0.5-(0.02*change1)))+((x>=(change1-10) & x<(change1-6))*(x+10.3-change1))+((x>=(change1-6) & x<(change1))*(4.3))+((x>=(change1) & x<(change1+10))*((-0.5*x)+4.3+(0.5*change1)))+((x>=(change1+10) & x<=(change1+15))*((-0.25*x)+1.8+(0.25*change1)))+((x>(change1+15) & x<=1000)*(-1.95)))+rnorm(length(x),sd=sds[i])+20	#Inject noise into base signal and store
	#	TestCases[i,71]<-paste(";",(i),sep="")	#Label signal for later identification
		SD_Change[i,"change"]<-change1	#Store transition point
}	#End loop
SD_Change[,"sd"]<-sds	#Store standard deviation of injected noise
write.csv(NoiseSeeds,row.names=FALSE,"./NoiseSeeds.csv")	#Save output
write.csv(TestCases,row.names=FALSE,"./TestCases.csv")	#Save output
write.csv(SD_Change,row.names=FALSE,"./SD_Change.csv")	#Save output
df <- as.data.frame(read.csv("TestCases.csv", header=T)) # read in data frame


#input number of frequency bands
j= c(1:6)

#input the original signal 
s <- as.vector(as.matrix((df[31,])))

#Averages<-t(Averages)
Averages = matrix(0,length(j),length(s))
nrows <- nrow(Averages)
rownames(Averages) <- 0: (nrow(Averages)-1)
colnames(Averages) <- 1:ncol(Averages)
Averages[1,] <- s


#Calculate Averages
for (j in 1:((nrows)-1)){
  for (n in (2*j):length(s)){
    #print(Averages[1, (n-(((2*j)-1)):n)])
   Averages[(j+1),n] <- mean(Averages[1, (n-((2*j)-1)):n]) 
    }
}

#Threshold Averages
Arow_1 <- Averages[2,2:70]
sigma <- (mad(Arow_1))/.6745
#print(mad(Arow_1))
Thresh<- sigma * (sqrt(2* log(length(Arow_1))))

for (i in 1:4){
  high <- Averages[i,] >= Thresh
  mid <- Averages[i,] < Thresh
  low <- Averages[i,] <= -Thresh
  Averages[i,high] <- (Averages[i,high] <- (Averages[i,high]-Thresh))
  Averages[i,mid] <- (Averages[i,mid] <- 0)
  Averages[i,low] <- (Averages[i,low] <- (Averages[i,low]+Thresh))
}


#Calculate Differences
Differences <- matrix(c(0),nrow(Averages)-1,ncol(Averages))

for (j in 1:((nrows)-1)){
  for (n in (2*(j)):length(s)){
    Differences[(j),n] <- (-1)*((mean(Averages[1, (n-((2*j)-1)):(n-j)])-mean(Averages[1, (n-(j)+1):n]))/2)
  }
}


#Plotting Results 
Differences1<- abs(Differences)
heatmap.2(Differences1,
  main = "Heatmap Soft Thresholding ",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )

plot(s, main = "Simulation Data", xlab= "Time", ylab="Brightness Level", xlim=c(7,70), ylim= c(14,28),type = "l", col = "red")
```
#Data Prep For Neural Network (Sobel Operators)

#Sobel Gradient 3x3
```{r}
horizx<- t(as.matrix(c(1,0,-1,2,0,-2,1,0,-1)))

a<- matrix(c(0),3,3)
k<-2
Differences3X3x <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3x[n,i] <- horizx %*% Z
    }
  }
}

horizy<- t(as.matrix(c(-1,-2,-1,0,0,0,1,2,1)))


Differences3X3y <- Differences

for(n in 2:4){
  for(i in 2:69){
      for (r in (n-1):(n+1)){
          a[r-(n-2),] <-c(Differences[r,(i-1):(i+1)]) 
              Z<-c(a[k-1,],a[k,],a[k+1,])
                  Differences3X3y[n,i] <- horizy %*% Z
    }
  }
}

Gradient3X3 <- sqrt((Differences3X3x)^2+(Differences3X3y)^2)
  
Differences2<- abs(Gradient3X3)
heatmap.2(Differences2,
  main = "3x3 Sobel Gradient ",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )

Gradient3X3Avg <- Gradient3X3
Gradient3X3Avg[3,] <- (colSums(Gradient3X3[2:4,])/3)
Gradient3X3Avg[1,] <- c(0)
Gradient3X3Avg[2,] <- c(0)
Gradient3X3Avg[4,] <- c(0)
Gradient3X3Avg[5,] <- c(0)

Differences6<- abs(Gradient3X3Avg)
heatmap.2(Differences6,
  main = "3x3 Sobel Gradient Averaged ",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )

Arow_1 <- Gradient3X3[3,2:70]
sigma <- (mad(Arow_1))/.6745
#print(mad(Arow_1))
Thresh<- sigma * (sqrt(2* log(length(Arow_1))))

for (i in 2:4){
  high <- Gradient3X3[i,] >= Thresh
  mid <- Gradient3X3[i,] < Thresh
  low <- Gradient3X3[i,] <= -Thresh
  Gradient3X3[i,high] <- (Gradient3X3[i,high] <- (Gradient3X3[i,high]-Thresh))
  Gradient3X3[i,mid] <- (Gradient3X3[i,mid] <- 0)
  Gradient3X3[i,low] <- (Gradient3X3[i,low] <- (Gradient3X3[i,low]+Thresh))
}

Gradient3X3[3,] <- (colSums(Gradient3X3[2:4,])/3)
Gradient3X3[1,] <- c(0)
Gradient3X3[2,] <- c(0)
Gradient3X3[4,] <- c(0)
Gradient3X3[5,] <- c(0)


Differences3<- abs(Gradient3X3)
heatmap.2(Differences3,
  main = "3x3 Sobel Gradient Averaged With Thresholding ",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )
```

#Sobel Gradient 5x5
```{r}
k<-3
Differences5X5x <- Differences
a<- matrix(c(0),5,5)

horizx<- t(as.matrix(c(1,2,0,-2,-1,4,8,0,-8,-4,6,12,0,-6,-12,4,8,0,-8,-4,1,2,0,-2,-1)))


for(i in 3:68){
    for (r in 1:5){
        a[r,] <-c(Differences[r,(i-2):(i+2)]) 
            Z<-c(a[k-2,],a[k-1,],a[k,],a[k+1,],a[k+2,])
                Differences5X5x[3,i] <- horizx %*% Z
  }
}

Differences5X5y <- Differences
a<- matrix(c(0),5,5)

horizy<- t(as.matrix(c(-1,-4,-6,-4,-1,-2,-8,-12,-8,-2,0,0,0,0,0,2,8,12,8,2,1,4,6,4,1)))


for(i in 3:68){
    for (r in 1:5){
        a[r,] <-c(Differences[r,(i-2):(i+2)]) 
            Z<-c(a[k-2,],a[k-1,],a[k,],a[k+1,],a[k+2,])
                Differences5X5y[3,i] <- horizy %*% Z
  }
}

Gradient5X5 <- sqrt((Differences5X5x)^2+(Differences5X5y)^2)

Differences4<- abs(Gradient5X5)
heatmap.2(Differences4,
  main = "5x5 Sobel Gradient",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )

Arow_1 <- Gradient5X5[3,2:70]
sigma <- (mad(Arow_1))/.6745
#print(mad(Arow_1))
Thresh<- sigma * (sqrt(2* log(length(Arow_1))))

for (i in 3:3){
  high <- Gradient5X5[i,] >= Thresh
  mid <- Gradient5X5[i,] < Thresh
  low <- Gradient5X5[i,] <= -Thresh
  Gradient5X5[i,high] <- (Gradient5X5[i,high] <- (Gradient5X5[i,high]-Thresh))
  Gradient5X5[i,mid] <- (Gradient5X5[i,mid] <- 0)
  Gradient5X5[i,low] <- (Gradient5X5[i,low] <- (Gradient5X5[i,low]+Thresh))
}

Differences5<- abs(Gradient5X5)
heatmap.2(Differences5,
  main = "5x5 Sobel Gradient With Thresholding",
  xlab = "Time",
  ylab = "Frequency",
  key=T, 
  keysize=1.5, 
  key.title = NA,
  symkey=TRUE, 
  notecol="black",            
  density.info="histogram",     
  trace="none",               
  margins =c(4,3),            
  dendrogram="none",           
  Rowv = FALSE,
  Colv = FALSE,
  srtCol = 1,
  cexRow = 1.0,
  breaks= 63,
  adjCol = c(0.5,1),
  col= grey.colors(62, start= 0.9, end=0.1, gamma=.7)
  )
```
